export enum QueryKeys {
    GET_ME = "GET_ME",
    GET_CONTACTS = "GET_CONTACTS",
    GET_ABOUT = "GET_ABOUT",
    GET_PUBLIC_OFFER = "GET_PUBLIC_OFFER",
    GET_USERS = "GET_USERS",
    GET_USER = "GET_USER",
    GET_ROLES = "GET_ROLES",
    GET_FAQ = "GET_FAQ",
    GET_MY_COURSES = "GET_MY_COURSES",
    GET_COURSE_SETS = "GET_COURSE_SETS",
    GET_ADMIN_USERS_FILTERS = "GET_ADMIN_USERS_FILTERS",
    GET_ADMIN_USERS_CREATE_OPTIONS = "GET_ADMIN_USERS_CREATE_OPTIONS",
    GET_TEACHERS = "GET_TEACHERS",
    GET_COURSE_PROGRAM = "GET_COURSE_PROGRAM",
    GET_COURSE_PROGRAM_LESSONS = "GET_COURSE_PROGRAM_LESSONS",
    GET_COURSE_REVIEWS = "GET_COURSE_REVIEWS",
}

export enum MutationKeys {
    AUTHENTICATE_ME = "UPDATE_ME",
    SIGN_UP = "SIGN_UP",
    UPDATE_ME = "UPDATE_ME",
    CHANGE_PASSWORD = "CHANGE_PASSWORD",
    DELETE_USER = "DELETE_USER",
    UPLOAD_FILE = "UPLOAD_FILE",
    ACTIVATE_USER = "ACTIVATE_USER",
    DEACTIVATE_USER = "DEACTIVATE_USER",
}
