export enum QueryKeys {
    GET_ME = "GET_ME",
    GET_CONTACTS = "GET_CONTACTS",
    GET_ABOUT = "GET_ABOUT",
    GET_PUBLIC_OFFER = "GET_PUBLIC_OFFER",
    GET_USERS = "GET_USERS",
    GET_USER = "GET_USER",
    GET_ROLES = "GET_ROLES",
    GET_FAQ = "GET_FAQ",
    GET_MY_COURSES = "GET_MY_COURSES",
    GET_COURSE_SETS = "GET_COURSE_SETS",
    GET_TEACHERS = "GET_TEACHERS",
    GET_COURSE_PROGRAM = "GET_COURSE_PROGRAM",
    GET_COURSE_PROGRAM_LESSONS = "GET_COURSE_PROGRAM_LESSONS",
    GET_COURSE_REVIEWS = "GET_COURSE_REVIEWS",
}

export enum MutationKeys {
    UPDATE_ME = "UPDATE_ME",
    CHANGE_PASSWORD = "CHANGE_PASSWORD",
    DELETE_USER = "DELETE_USER",
    UPLOAD_AVATAR = "UPLOAD_AVATAR",
    UPLOAD_IMAGE = "UPLOAD_IMAGE",
    UPLOAD_DOCUMENT = "UPLOAD_DOCUMENT",
    UPLOAD_VIDEO = "UPLOAD_VIDEO",
    ACTIVATE_USER = "ACTIVATE_USER",
    DEACTIVATE_USER = "DEACTIVATE_USER",
}
