export enum TableOperationType {
    INSERT_TABLE = "INSERT_TABLE",
    DELETE_TABLE = "DELETE_TABLE",
    ADD_COLUMN_BEFORE = "ADD_COLUMN_BEFORE",
    ADD_COLUMN_AFTER = "ADD_COLUMN_AFTER",
    DELETE_COLUMN = "DELETE_COLUMN",
    ADD_ROW_BEFORE = "ADD_ROW_BEFORE",
    ADD_ROW_AFTER = "ADD_ROW_AFTER",
    DELETE_ROW = "DELETE_ROW",
    MERGE_CELLS = "MERGE_CELLS",
    SPLIT_CELL = "SPLIT_CELL",
    TOGGLE_HEADER_ROW = "TOGGLE_HEADER_ROW",
    TOGGLE_HEADER_COLUMN = "TOGGLE_HEADER_COLUMN",
}
