version: "3.8"
services:
    front:
        image: registry.addamant-work.ru/lms-addamant/addamant-lms/master
        networks:
            - swarm
            - lms-microservices
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.hostname==test
    front_balancer:
        image: registry.addamant-work.ru/lms-addamant/addamant-lms/develop/balancer
        networks:
            - swarm
            - lms-microservices_dev
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.hostname==test
networks:
    swarm:
        external: true
    lms-microservices:
        external: true
