version: "3.8"
services:
    front:
        image: registry.addamant-work.ru/lms-addamant/addamant-lms/develop
        networks:
            - swarm
            - lms-microservices_dev
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.hostname==develop
    front_balancer:
        image: registry.addamant-work.ru/lms-addamant/addamant-lms/develop/balancer
        environment: 
            FRONTEND_URL: http://lms_dev_front:3000
            MINIO_PROXY_URL: http://192.168.0.45:9010
            MINIO_BUCKET: lms-dev-public
        networks:
            - swarm
            - lms-microservices_dev
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.hostname==develop
networks:
    swarm:
        external: true
    lms-microservices_dev:
        external: true
