FROM nginx:alpine AS result

WORKDIR /var/www/html

RUN mkdir -p /tmp/cache/nginx_minio_cache

COPY  ./.next/static ./.next/static
COPY  ./public ./.next/public

RUN rm /etc/nginx/conf.d/*

COPY ./docker/nginx.conf.template /etc/nginx/conf.d/nginx.conf

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]