import GroupList from "./List";
import StudentList from "./StudentList";
import GroupSchedule from "./GroupSchedule";
export * from "./CreateGroupForm";
export * from "./EditGroupForm";
export * from "./DeleteGroupModal";
export * from "./CreateScheduleForm";
export * from "./DeleteScheduleModal";
export * from "./EditScheduleForm";
export { GroupList, StudentList, GroupSchedule };
